name: CI

on:
  push:
    branches: [ master, zio-1.x ]
  pull_request:
    branches: [ master, zio-1.x ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: docker-practice/actions-setup-docker@master
        with:
            docker_channel: stable
            docker_version: 20.10
      - name: Validate Scaladoc
        run: sbt doc
      - name: Run tests
        run: sbt +test +IntegrationTest/test
